### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by VidyaPuri** [linusg/xbox360controller#6] opened 2018-07-15 10:42 UTC
Greetings,
i tried installing the package and i get this error:

after issuing pip3 install -U xbox360controller

i get:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-idoeikld/xbox360controller/setup.py", line 4, in <module>
        with open('README.md', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

do you have any idea what is it about?

thank you very much!

**Comment by linusg** [comment] 2018-07-15 11:23
Hi!

I can reproduce this issue. Let me explain:

```python
with open('README.md', 'r') as f:
    long_description = f.read()
```

Here I'm trying to open the README to use it later as the long description for PyPI. This works when building the package from the full repository, but since I do not ship the README with the distributed package, it fails doing exactly that when installing from PyPI using pip.

Let me fix this; I'll come back to you shortly.

Thanks for reporting!

**Comment by linusg** [comment] 2018-07-15 11:33
> but since I do not ship the README with the distributed package

Actually that's wrong. I'll investigate.

**Comment by linusg** [comment] 2018-07-15 11:55
Alright, the new working version is on PyPI. Please try installing again!
I'll close this for now, feel free to reopen if the issue is still not resolved for you.
Thanks for reporting, come back to me at any time if you have further questions!

**Closed as completed by linusg** 2018-07-15 11:55 UTC
Labels: bug

**Comment by VidyaPuri** [comment] 2018-07-15 20:14
Greetings,
now it worked out and i managed to install it. But kind of having a problem using it.

I tried playing around with the "Basics" code you have on Readme.md.

running it with sudo i manage to get it to run, but it doesn't do anything. No processes are called when axis is moved or button A is pressed. Am i missing something? 
regards,
V

**Comment by linusg** [comment] 2018-07-15 20:56
To clear up, you run exactly this code:

```
import signal
from xbox360controller import Xbox360Controller


def on_button_pressed(button):
    print('Button {0} was pressed'.format(button.name))


def on_button_released(button):
    print('Button {0} was released'.format(button.name))


def on_axis_moved(axis):
    print('Axis {0} moved to {1} {2}'.format(axis.name, axis.x, axis.y))

try:
    with Xbox360Controller(0, axis_threshold=0.2) as controller:
        # Button A events
        controller.button_a.when_pressed = on_button_pressed
        controller.button_a.when_released = on_button_released

        # Left and right axis move event
        controller.axis_l.when_moved = on_axis_moved
        controller.axis_r.when_moved = on_axis_moved

        signal.pause()
except KeyboardInterrupt:
    pass
```

using an **official Microsoft Xbox 360 controller** and get no output when **pressing the A button or moving the left or right axis**. Right?

- What Linux Ditribution and version are you running the code on? What Python version exactly? (shouldn't be source of the problem, just to be sure)
- What's the output of the following:

```
with Xbox360Controller(0) as controller:
    controller.info()
```

?

**Comment by VidyaPuri** [comment] 2018-07-16 12:11
Yes, i ran the code above and there was no output when i used the controller. 
I am using Ubuntu 16.04, the python is 3.5.

The output i will check as soon as i get back to the computer!

**Comment by linusg** [comment] 2018-07-16 12:16
> The output i will check as soon as i get back to the computer!

Sure. Please confirm what I wrote above applies to you:

> using an official Microsoft Xbox 360 controller and get no output when pressing the A button or moving the left or right axis.

**Comment by VidyaPuri** [comment] 2018-07-17 17:19
I am using official Xbox 360 MS controller and get no output when pressing A or using any of the two axes. 
When running the code from above i get:

> Warning: Setting the LED status is not supported for
this gamepad or its driver.
VirtualBox USB Tablet at index 0
Axes: 5
	axis_l
	axis_r
	hat
	trigger_l
	trigger_r
Buttons: 11
	button_a
	button_b
	button_x
	button_y
	button_trigger_l
	button_trigger_r
	button_select
	button_start
	button_mode
	button_thumb_l
	button_thumb_r
Rumble: no
Driver version: 2.1.0 1.0.1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vidya/Dokumenti/xbox360controller/xbox360controller/controller.py", line 263, in _event_loop
    event = self.get_event()
  File "/home/vidya/Dokumenti/xbox360controller/xbox360controller/controller.py", line 270, in get_event
    r, w, e = select.select([self._dev_file], [], [], 0)
OSError: [Errno 9] Bad file descriptor

**Comment by linusg** [comment] 2018-07-17 17:49
> VirtualBox USB Tablet at index 0

That's probably the cause. Are you running this in a virtual machine? Seems like the device at index 0 is the VirtualBox Tablet (I guess this can be changed between mouse and Tablet mode in the settings), also it (of course) reports no rumble and LED functionality. Make sure you allow the VM access to your hosts USB Port where the controller is attached and try index 1 or 2.

**Comment by VidyaPuri** [comment] 2018-07-17 17:56
Yes, i am using VM. The permissions are set, because i managed to get to the raw data through xboxdrv driver

> sudo xboxdrv --detach-kernel-driver

and also i tried using it with pygame and it works.

I tried both index 1 and 2 and i get the same error.

**Comment by linusg** [comment] 2018-07-17 18:00
Please, what's the output of:

```
for i in range(10):
    with Xbox360Controller(i) as controller:
        controller.info()
```

I never tested this in a VM nor even used my controller in a VM, so I'm not sure how far I can assist here.
